"""The v4 schema, split by lifecycle.

This was one 2,187-line module holding 106 models and 22 type aliases -- manifests, change
graphs, work units, rendered prompts, gold judgments, candidates, findings, evidence,
opportunity records, run plans and the judge's verdicts -- imported by 83 other modules. Every
one of them depended on all of it, so a change to any record risked all of them, and the file
was the single largest coupling point in the tree.

Split by **lifecycle**, not by concern. Concern would have been the obvious cut and would have
been wrong: the concern taxonomy is itself unreliable -- 11 of the 19 gold obligations labelled
`style` are `grind` simplifications and `encard_` renames -- so cutting the domain model along
it would bake an unstable vocabulary into the structure.

    base          the strict-model base and schema version constants
    identity      what a review is about -- dataset, episodes, change graph, work units, prompts
    gold          maintainer ground truth (gold-bearing; generation must not import it)
    findings      candidate -> finding -> issue, and the synthesis records between them
    evidence      warrants: what was checked and which tier of evidence it is
    opportunities the systematic-opportunity pipeline
    runs          pre-registration and receipts
    scoring       the judge's unit of work and its verdict

The one boundary worth stating plainly: `gold` is the only gold-bearing module here, and
nothing in generation may import it.

This module re-exports every name, so `from .schema import X` resolves exactly as before.
That is deliberate: rewriting 83 importers in the same change as the split would make the
split unreviewable. Importers move to the submodule they actually need as they are touched,
and this list shrinks.
"""

from .base import (  # noqa: F401
    CHANGE_GRAPH_SCHEMA_VERSION,
    EPISODE_SCHEMA_VERSION,
    EVENT_SCHEMA_VERSION,
    MANIFEST_SCHEMA_VERSION,
    StrictModel,
)

from .identity import (  # noqa: F401
    ArtifactRef,
    ChangeFileCoverage,
    ChangeGraph,
    ChangeTarget,
    ChangeTargetKind,
    ChangedRange,
    ComponentKind,
    DatasetManifest,
    DescriptionProvenance,
    EventType,
    FunnelDecision,
    LifecycleFacet,
    LineSpan,
    ModificationComponent,
    ModificationRecord,
    PRRelation,
    PromptPrecedent,
    RelationEvidence,
    RenderedPrompt,
    RetrievalCutoff,
    ReviewEpisodeBoundary,
    ReviewEpisodeInput,
    ReviewRoundSegment,
    ReviewWorkUnit,
    SemanticEntity,
    SourceEvent,
    SubjectKind,
    VisibleText,
)

from .gold import (  # noqa: F401
    DecomposedObligationSpec,
    InterventionScopeMigration,
    InterventionView,
    JudgmentAction,
    JudgmentAnnotation,
    JudgmentContextRelation,
    JudgmentDecompositionDecision,
    JudgmentNode,
    JudgmentObligation,
    JudgmentScopeRelation,
    OutcomeObservation,
    PilotCase,
    ScopeResolution,
)

from .findings import (  # noqa: F401
    ARMS,
    CandidateClaim,
    CandidateRejection,
    ConcernFamily,
    ConflictRecord,
    EvidenceRequest,
    FILE_COHERENCE_SPEC,
    FILE_GENERALIST_ARM,
    FindingSource,
    GENERALIST_ARM,
    IssueKind,
    PRODUCING_ARMS,
    ProposedEdit,
    RETIRED_ARM_SPELLINGS,
    ReviewFinding,
    ReviewIssue,
    SynthesisAnchor,
    SynthesisDecision,
    SynthesisMatchProjection,
    SynthesizedFinding,
)

from .evidence import (  # noqa: F401
    AdjudicationVerificationArtifact,
    EVIDENCE_TIERS,
    EvidenceArtifact,
    EvidenceAssertion,
    EvidencePacket,
    EvidenceTier,
    OpportunityEvidenceArtifact,
    ResidualCandidateVerificationArtifact,
    SelectedFinding,
    evidence_rank,
)

from .opportunities import (  # noqa: F401
    AdjudicationBundle,
    AdjudicationConsensus,
    AdjudicationVote,
    CandidateOpportunityLink,
    CanonicalRetrievalHit,
    CapabilityAssessment,
    CitedAdjudicationClaim,
    CompositionSource,
    FixedPipelineOpportunityLedger,
    HistoricalTransformationHit,
    HistoricalTransformationQuery,
    HistoricalTransformationRecord,
    HistoricalTransformationRequest,
    HistoricalTransformationResolution,
    HistoricalTransformationStoreManifest,
    HistoricalTransformationTrigger,
    ImplementationCapability,
    InvestigationMethod,
    InvestigationRecord,
    InvestigationTask,
    ManualAgendaProbeTask,
    MethodApplicability,
    MethodExpressionContract,
    NameCollisionResult,
    NamingPopulationMember,
    NormAssessment,
    NormRecord,
    NormScope,
    OperatorRun,
    OpportunityAdjudication,
    OpportunityMethod,
    OpportunityTransformation,
    OpportunityTreatmentManifest,
    OracleOpportunity,
    OracleOpportunityEvidence,
    RedundancyRequest,
    RepositoryDeclaration,
    ResidualReviewPass,
    ReviewOpportunity,
    SemanticSubjectInference,
    TechnicalAssessment,
    WorthinessDecision,
    WrapperCompositionPlan,
)

from .runs import (  # noqa: F401
    EvaluationProtocol,
    EvaluationReceipt,
    GenerationPlanV2,
    GenerationRunReceipt,
    PairManifest,
    PairingTier,
    RunManifest,
    RunPlan,
)

from .scoring import (  # noqa: F401
    SemanticMatch,
    SemanticPair,
)


__all__ = [
    "ARMS",
    "AdjudicationBundle",
    "AdjudicationConsensus",
    "AdjudicationVerificationArtifact",
    "AdjudicationVote",
    "ArtifactRef",
    "CHANGE_GRAPH_SCHEMA_VERSION",
    "CandidateClaim",
    "CandidateOpportunityLink",
    "CandidateRejection",
    "CanonicalRetrievalHit",
    "CapabilityAssessment",
    "ChangeFileCoverage",
    "ChangeGraph",
    "ChangeTarget",
    "ChangeTargetKind",
    "ChangedRange",
    "CitedAdjudicationClaim",
    "ComponentKind",
    "CompositionSource",
    "ConcernFamily",
    "ConflictRecord",
    "DatasetManifest",
    "DecomposedObligationSpec",
    "DescriptionProvenance",
    "EPISODE_SCHEMA_VERSION",
    "EVENT_SCHEMA_VERSION",
    "EVIDENCE_TIERS",
    "EvaluationProtocol",
    "EvaluationReceipt",
    "EventType",
    "EvidenceArtifact",
    "EvidenceAssertion",
    "EvidencePacket",
    "EvidenceRequest",
    "EvidenceTier",
    "FILE_COHERENCE_SPEC",
    "FILE_GENERALIST_ARM",
    "FindingSource",
    "FixedPipelineOpportunityLedger",
    "FunnelDecision",
    "GENERALIST_ARM",
    "GenerationPlanV2",
    "GenerationRunReceipt",
    "HistoricalTransformationHit",
    "HistoricalTransformationQuery",
    "HistoricalTransformationRecord",
    "HistoricalTransformationRequest",
    "HistoricalTransformationResolution",
    "HistoricalTransformationStoreManifest",
    "HistoricalTransformationTrigger",
    "ImplementationCapability",
    "InterventionScopeMigration",
    "InterventionView",
    "InvestigationMethod",
    "InvestigationRecord",
    "InvestigationTask",
    "IssueKind",
    "JudgmentAction",
    "JudgmentAnnotation",
    "JudgmentContextRelation",
    "JudgmentDecompositionDecision",
    "JudgmentNode",
    "JudgmentObligation",
    "JudgmentScopeRelation",
    "LifecycleFacet",
    "LineSpan",
    "MANIFEST_SCHEMA_VERSION",
    "ManualAgendaProbeTask",
    "MethodApplicability",
    "MethodExpressionContract",
    "ModificationComponent",
    "ModificationRecord",
    "NameCollisionResult",
    "NamingPopulationMember",
    "NormAssessment",
    "NormRecord",
    "NormScope",
    "OperatorRun",
    "OpportunityAdjudication",
    "OpportunityEvidenceArtifact",
    "OpportunityMethod",
    "OpportunityTransformation",
    "OpportunityTreatmentManifest",
    "OracleOpportunity",
    "OracleOpportunityEvidence",
    "OutcomeObservation",
    "PRODUCING_ARMS",
    "PRRelation",
    "PairManifest",
    "PairingTier",
    "PilotCase",
    "PromptPrecedent",
    "ProposedEdit",
    "RETIRED_ARM_SPELLINGS",
    "RedundancyRequest",
    "RelationEvidence",
    "RenderedPrompt",
    "RepositoryDeclaration",
    "ResidualCandidateVerificationArtifact",
    "ResidualReviewPass",
    "RetrievalCutoff",
    "ReviewEpisodeBoundary",
    "ReviewEpisodeInput",
    "ReviewFinding",
    "ReviewIssue",
    "ReviewOpportunity",
    "ReviewRoundSegment",
    "ReviewWorkUnit",
    "RunManifest",
    "RunPlan",
    "ScopeResolution",
    "SelectedFinding",
    "SemanticEntity",
    "SemanticMatch",
    "SemanticPair",
    "SemanticSubjectInference",
    "SourceEvent",
    "StrictModel",
    "SubjectKind",
    "SynthesisAnchor",
    "SynthesisDecision",
    "SynthesisMatchProjection",
    "SynthesizedFinding",
    "TechnicalAssessment",
    "VisibleText",
    "WorthinessDecision",
    "WrapperCompositionPlan",
    "evidence_rank",
]
